### ISSUE TITLE
Primary slider not working in  foreach

### ISSUE THREAD

**Issue by madmouse17** [ahmadHuss/ludus-free-premium-ecommerce-template#1]
```javascript
<div class="s-skeleton s-skeleton--h-640 s-skeleton--bg-grey">
    <div class="owl-carousel primary-style-3" id="hero-slider">
        @foreach ($baner as $banner)
        <div class="hero-slide hero-slide--7" style="background-image:url({{ asset('baner/thumbnail/'.$banner->image) }})">
         </div>
         @endforeach
    </div>
 </div>
```

hi, how do I repeat the primary slider in the css in one line, when I use css in one line there is a problem because the primary slider can't be responsive on the desktop and for the mobile version there is no problem

**Comment by ahmadhuss** [comment]
Hi, @madmouse17

**How do I repeat the primary slider in the CSS in one line?**
It seems like you're using `foreach` loop and want to dynamically add background images. You can do this in one line but every slide in the primary slider also contains some titles and links. However, If you want to dynamically add background images without slide content you can do something like this. I am assuming your banner objects are in the array.


```php
class Banner {
            public $image = '';
            public function __construct($image = '') {
                $this->image = $image;
            }
         }

        $banners = [
            new Banner('slide-7.jpg'),
            new Banner('slide-8.jpg'),
            new Banner('slide-9.jpg')
         ];

        <!--====== Primary Slider ======-->
        <div class="s-skeleton s-skeleton--h-640 s-skeleton--bg-grey">
            <div class="owl-carousel primary-style-3" id="hero-slider">
                @foreach($banners as $banner)
                    <div class="hero-slide" style="background-image:url({{ asset("images/slider/$banner->image") }})"></div>
                @endforeach
                </div>
            </div>
        </div>
        <!--====== End - Primary Slider ======-->


```

But if you want to render the content of the slide too, you can manipulate the array and make a nested array structure that contains the content of the slide and render the HTML markup according to the array structure. Your array structure should be something like this.

```php
$banners = [
 0 => [
'image' => $BannerImageInstance1,
 'content' => [
   'title' => 'Update Your Fashion',
   'subtitle '=> '10% Discount on Outwear',
   'subtitle2' => 'Find outwear on best prices',
   'text' => 'Starting At'
   'priceText' => '$100.00',
   'linkText'  => 'SHOP NOW'
],

 1 => [
'image' => $BannerImageInstance2,
 'content' => [
   'title' => 'Update Your Fashion',
   'subtitle '=> '10% Discount on Outwear',
   'subtitle2' => 'Find outwear on best prices',
   'text' => 'Starting At'
   'priceText' => '$100.00',
   'linkText'  => 'SHOP NOW'
],

 2 => [
'image' => $BannerImageInstance3,
 'content' => [
   'title' => 'Update Your Fashion',
   'subtitle '=> '10% Discount on Outwear',
   'subtitle2' => 'Find outwear on best prices',
   'text' => 'Starting At'
   'priceText' => '$100.00',
   'linkText'  => 'SHOP NOW'
]

]

```

I hope it is clear now.

**Comment by madmouse17** [comment]
![not responsive](https://user-images.githubusercontent.com/33163281/115958338-41bfc700-a531-11eb-8104-f5f2b19ae6e2.png)
still not responsive, there is a blank page under the banner

https://user-images.githubusercontent.com/33163281/115958871-864c6200-a533-11eb-9e0f-09fb12d5d5f3.mp4

**Comment by madmouse17** [comment]
https://user-images.githubusercontent.com/33163281/115958749-da0a7b80-a532-11eb-9a7c-e38096987236.mp4

```javascript
<div class="s-skeleton s-skeleton--h-640 s-skeleton--bg-grey">
    <div class="owl-carousel primary-style-3" id="hero-slider">
        @foreach ($baner as $banner)
        <div class="hero-slide" style="background-image:url({{ asset('baner/thumbnail/'.$banner->image) }})">
        </div>
        <div></div>
        @endforeach
    </div>
</div>
```

banner becomes responsive after adding a **div** below the banner slide but the next banner is blank
